
export const COLOR_SCHEMES = {
  blue: {
    bg: "bg-blue-100",
    text: "text-blue-600",
    bgDark: "bg-blue-600",
    textLight: "text-blue-100",
    border: "border-blue-200",
    bgLight: "bg-blue-50",
    hoverBg: "hover:bg-blue-100",
    focusBorder: "focus:border-blue-500",
  },
  purple: {
    bg: "bg-purple-100",
    text: "text-purple-600",
    bgDark: "bg-purple-600",
    textLight: "text-purple-100",
    border: "border-purple-200",
    bgLight: "bg-purple-50",
    hoverBg: "hover:bg-purple-100",
    focusBorder: "focus:border-purple-500",
  },
  green: {
    bg: "bg-green-100",
    text: "text-green-600",
    bgDark: "bg-green-600",
    textLight: "text-green-100",
    border: "border-green-200",
    bgLight: "bg-green-50",
    hoverBg: "hover:bg-green-100",
    focusBorder: "focus:border-green-500",
  },
  emerald: {
    bg: "bg-emerald-100",
    text: "text-emerald-600",
    bgDark: "bg-emerald-600",
    textLight: "text-emerald-100",
    border: "border-emerald-200",
    bgLight: "bg-emerald-50",
    hoverBg: "hover:bg-emerald-100",
    focusBorder: "focus:border-emerald-500",
    icon: "oklch(69.6% 0.17 162.48)",
  },
  red: {
    bg: "bg-red-100",
    text: "text-red-600",
    bgDark: "bg-red-600",
    textLight: "text-red-100",
    border: "border-red-200",
    bgLight: "bg-red-50",
    hoverBg: "hover:bg-red-100",
    focusBorder: "focus:border-red-500",
    icon: "oklch(57.7% 0.245 27.325)"
  },
  orange: {
    bg: "bg-orange-100",
    text: "text-orange-600",
    bgDark: "bg-orange-600",
    textLight: "text-orange-100",
    border: "border-orange-200",
    bgLight: "bg-orange-50",
    hoverBg: "hover:bg-orange-100",
    focusBorder: "focus:border-orange-500",
    icon: "oklch(75% 0.183 55.934)"
  },
  amber: {
    bg: "bg-amber-100",
    text: "text-amber-600",
    bgDark: "bg-amber-600",
    textLight: "text-amber-100",
    border: "border-amber-200",
    bgLight: "bg-amber-50",
    hoverBg: "hover:bg-amber-100",
    focusBorder: "focus:border-amber-500",
    icon: "oklch(66.6% 0.179 58.318)"
  },
  yellow: {
    bg: "bg-yellow-100",
    text: "text-yellow-600",
    bgDark: "bg-yellow-600",
    textLight: "text-yellow-100",
    border: "border-yellow-200",
    bgLight: "bg-yellow-50",
    hoverBg: "hover:bg-yellow-100",
    focusBorder: "focus:border-yellow-500",
    icon: "oklch(79.5 % 0.184 86.047)"
  },
  gray: {
    bg: "bg-gray-100",
    text: "text-gray-600",
    bgDark: "bg-gray-600",
    textLight: "text-gray-100",
    border: "border-gray-200",
    bgLight: "bg-gray-50",
    hoverBg: "hover:bg-gray-100",
    focusBorder: "focus:border-gray-500",
  },
  indigo: {
    bg: "bg-indigo-100",
    text: "text-indigo-600",
    bgDark: "bg-indigo-600",
    textLight: "text-indigo-100",
    border: "border-indigo-200",
    bgLight: "bg-indigo-50",
    hoverBg: "hover:bg-indigo-100",
    focusBorder: "focus:border-indigo-500",
  },
  violet: {
    bg: "bg-violet-100",
    text: "text-violet-600",
    bgDark: "bg-violet-600",
    textLight: "text-violet-100",
    border: "border-violet-200",
    bgLight: "bg-violet-50",
    hoverBg: "hover:bg-violet-100",
    focusBorder: "focus:border-violet-500",
  },
};

export const ALERT_STYLES = {
  warning: {
    bg: "bg-yellow-50",
    border: "border-yellow-200",
    icon: "text-yellow-600",
    title: "text-yellow-900",
    message: "text-yellow-800",
    button: "bg-yellow-600 hover:bg-yellow-700",
  },
  info: {
    bg: "bg-blue-50",
    border: "border-blue-200",
    icon: "text-blue-600",
    title: "text-blue-900",
    message: "text-blue-800",
    button: "bg-blue-600 hover:bg-blue-700",
  },
  error: {
    bg: "bg-red-50",
    border: "border-red-200",
    icon: "text-red-600",
    title: "text-red-900",
    message: "text-red-800",
    button: "bg-red-600 hover:bg-red-700",
  },
  success: {
    bg: "bg-green-50",
    border: "border-green-200",
    icon: "text-green-600",
    title: "text-green-900",
    message: "text-green-800",
    button: "bg-green-600 hover:bg-green-700",
  },
};

export const getColorScheme = (color) => {
  return COLOR_SCHEMES[color] || COLOR_SCHEMES.gray;
};
